version: '3'

services:
    web:
        container_name: web
        build: ./web
        environment: 
            - APACHE_RUN_USER=www-data
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
            - 8080:80
        working_dir: ${APP_PATH_CONTAINER}

    db:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123
        volumes: 
            - ${DB_PATH_HOST}:/var/lib/mysql

    adminer:
        container_name: adminer        
        image: adminer
        restart: always
        ports:
            - 6080:8080

    composer:
        container_name: composer   
        image: composer:2.0.13
        volumes: 
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install